# Generated by Django 5.0.14 on 2025-11-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apparcar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="name",
            field=models.CharField(
                max_length=100, verbose_name="Nombre del estacionamiento"
            ),
        ),
        migrations.AlterField(
            model_name="parking",
            name="nearby_place",
            field=models.TextField(blank=True, verbose_name="Lugares cercanos"),
        ),
    ]
