# Generated by Django 5.0.14 on 2025-11-10 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apparcar", "0002_alter_parking_name_alter_parking_nearby_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="nearby_place",
            field=models.CharField(max_length=100),
        ),
    ]
