# Generated by Django 5.0.14 on 2025-11-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apparcar", "0003_alter_parking_nearby_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkingsession",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
