# Generated by Django 5.0.14 on 2025-11-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apparcar", "0004_parkingsession_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="parking",
            name="embedding",
            field=models.JSONField(
                blank=True, help_text="Embedding semántico (lista de floats)", null=True
            ),
        ),
    ]
