# Generated by Django 5.0.14 on 2025-11-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apparcar", "0005_parking_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parking",
            name="nearby_place",
            field=models.CharField(max_length=200),
        ),
    ]
